import { useCallback, useEffect, useState } from "react";
const money = n => new Intl.NumberFormat("en-IN", {style:"currency",currency:"INR"}).format(Number(n || 0));
const date = n => n ? new Date(n).toLocaleString([], {dateStyle:"medium",timeStyle:"short"}) : "—";
const name = d => d.fullName || d.account.email.split("@")[0];
const labels = {PENDING:"In queue · awaiting approval",CONFIRMED:"In queue · confirmed",IN_PROGRESS:"In progress",COMPLETED:"Completed",CANCELLED:"Cancelled"};
function ErrorBox({error}) { return error ? <p className="form-message" role="alert">{error}</p> : null; }

export default function Dashboard({session,doctors,doctorError,loadDoctors,book,api}) {
  const [tab,setTab] = useState("overview"), [visits,setVisits] = useState(null), [stats,setStats] = useState(null), [error,setError] = useState(""), [revision,setRevision] = useState(0);
  const role=session.role, patient=role==="PATIENT", doctor=role==="DOCTOR";
  const refresh=useCallback(()=>setRevision(n=>n+1),[]);
  useEffect(()=>{
    let active=true; setError("");
    Promise.all([api(role==="CLINIC_ADMIN"?"/api/appointments":"/api/appointments/my"),api("/api/dashboard")])
      .then(([v,s])=>{if(active){setVisits(v);setStats(s);}})
      .catch(e=>{if(active)setError(e.message);});
    return ()=>{active=false;};
  },[api,role,revision]);
  const tabs=[["overview","Dashboard"],...(patient?[["doctors","Doctors"]]:[]),["bookings",patient?"My bookings":"Appointments"],["invoices",patient?"Medicines & invoices":"Invoices & earnings"],...(doctor?[["schedule","Availability"]]:[]),...(role==="CLINIC_ADMIN"?[["accounts","Doctors & patients"]]:[])];
  return <div className="workspace"><aside className="sidebar"><p className="eyebrow">Your workspace</p><nav aria-label="Dashboard sections">{tabs.map(([key,label])=><button key={key} aria-current={tab===key?"page":undefined} onClick={()=>setTab(key)}>{label}</button>)}</nav><div className="sidebar-note">A little clarity.<br/>Better connected care.</div></aside>
    <main className="workspace-main"><header className="workspace-header"><div><p className="eyebrow">{patient?"Patient":doctor?"Doctor":"Administrator"} dashboard</p><h1>Your care, connected.</h1><p className="muted">Signed in as {session.email}</p></div><div className="header-count"><strong>{stats?.completedVisits ?? "…"}</strong><span>Completed consultations</span>{!patient&&<small>{stats?.patientsConsulted ?? "…"} patients consulted</small>}</div></header>
      <ErrorBox error={error}/><button className="text-button refresh" onClick={refresh}>Refresh appointments</button>
      {tab==="overview"&&<><div className="metrics"><Metric label="In queue" value={stats?.inQueue}/><Metric label="In progress" value={stats?.inProgress}/><Metric label="Consultations completed" value={stats?.completedVisits}/><Metric label={patient?"Demo payments":"Demo doctor earnings"} value={stats?money(patient?stats.demoGrossRevenue:stats.demoDoctorEarnings):"…"}/></div>
        {!patient&&<div className="metrics secondary-metrics"><Metric label="Patients consulted" value={stats?.patientsConsulted}/><Metric label="Patients reported recovered" value={stats?.patientsReportedRecovered}/><Metric label="In-person referrals" value={stats?.inPersonReferrals}/><Metric label="Outstanding invoices" value={stats?money(stats.outstanding):"…"}/></div>}
        <p className="muted small-note">Recovery counts reflect doctor-recorded outcomes, not a guarantee of cure.</p>
        {patient&&<section><div className="section-head"><h2>Your care team</h2><button className="text-button" onClick={()=>setTab("doctors")}>See all doctors</button></div><Doctors doctors={doctors.slice(0,3)} book={book} error={doctorError}/></section>}
        <section className="dashboard-section"><div className="section-head"><h2>{patient?"Your recent visits":"Appointment activity"}</h2><button className="text-button" onClick={()=>setTab("bookings")}>View all bookings</button></div><VisitList visits={visits?.slice(-3).reverse()} role={role} api={api} refresh={refresh} demo={stats?.demoPaymentsEnabled}/></section></>}
      {tab==="doctors"&&<section><h2>Find your doctor</h2><Doctors doctors={doctors} book={book} error={doctorError}/></section>}
      {tab==="bookings"&&<Bookings visits={visits} role={role} api={api} refresh={refresh} demo={stats?.demoPaymentsEnabled}/>}
      {tab==="invoices"&&<section><h2>{patient?"Your medicines & invoices":"Invoices & earnings"}</h2><p className="demo-banner">Demo payment mode. No money is collected and no medicine is dispatched.</p><div className="metrics"><Metric label={patient?"Doctor fees (demo paid)":"Doctor earnings (demo)"} value={stats?money(stats.demoDoctorEarnings):"…"}/><Metric label="Medicine charges (demo paid)" value={stats?money(stats.demoMedicineRevenue):"…"}/><Metric label="Total demo payments" value={stats?money(stats.demoGrossRevenue):"…"}/><Metric label="Outstanding" value={stats?money(stats.outstanding):"…"}/></div>{role==="CLINIC_ADMIN"&&<p className="muted">This is a fee breakdown, not profit. Pharmacy costs, commissions, taxes, and refunds are not configured.</p>}<VisitList visits={visits?.filter(a=>a.invoice)} role={role} api={api} refresh={refresh} demo={stats?.demoPaymentsEnabled}/></section>}
      {tab==="schedule"&&<Schedule api={api} visits={visits||[]} refresh={refresh}/>}
      {tab==="accounts"&&<Accounts api={api} doctors={doctors} loadDoctors={loadDoctors}/>}
    </main></div>;
}
function Metric({label,value}) {return <div className="metric"><span>{label}</span><strong>{value??"…"}</strong></div>;}
function Doctors({doctors,book,error}) {return <><ErrorBox error={error}/><div className="doctor-grid">{doctors.map(d=><article className="doctor" key={d.id}><div className="doctor-avatar">{name(d).slice(0,1)}</div><p className="specialty">{d.specialization}</p><h2>Dr. {name(d)}</h2><p>{d.yearsOfExperience} years of experience</p><p>{money(d.consultationFee)} consultation fee</p><button className="text-button" onClick={()=>book(d)}>See available times →</button></article>)}</div>{!doctors.length&&<p className="empty">No doctors available.</p>}</>;}
function Bookings(props) {
  const [filter,setFilter]=useState("ALL");
  const filtered=props.visits?.filter(a=>filter==="ALL"||filter==="QUEUE"&&["PENDING","CONFIRMED"].includes(a.status)||a.status===filter);
  return <section><h2>Appointment history</h2><div className="filter-tabs">{[["ALL","All"],["QUEUE","In queue"],["IN_PROGRESS","In progress"],["COMPLETED","Completed"],["CANCELLED","Cancelled"]].map(([key,label])=><button key={key} aria-pressed={filter===key} onClick={()=>setFilter(key)}>{label}</button>)}</div><VisitList {...props} visits={filtered}/></section>;
}
function VisitList({visits,...props}) {return visits===null||visits===undefined?<p>Loading appointments…</p>:visits.length?<div className="appointment-list">{visits.map(a=><Visit key={a.id} a={a} {...props}/>)}</div>:<p className="empty">No appointments in this view.</p>;}
function Visit({a,role,api,refresh,demo}) {
  const [busy,setBusy]=useState(false),[error,setError]=useState(""),[confirm,setConfirm]=useState(false);
  async function act(path,body,method="POST") {setBusy(true);setError("");try{await api(path,{method,...(body?{body:JSON.stringify(body)}:{})});setConfirm(false);refresh();}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <article className="visit-card"><div className="section-head"><div><h3>{role==="PATIENT"?"Dr. "+name(a.doctor):a.patient.fullName}</h3><p>Visit #{a.id} · {date(a.slot.startTime)}</p><small>{role!=="PATIENT"?"Dr. "+name(a.doctor)+" · ":""}{a.doctor.specialization}</small></div><span className="status">{labels[a.status]}</span></div><p>{a.reasonForVisit}</p><ErrorBox error={error}/>
    {a.diagnosis&&<div className="visit-notes"><strong>Consultation notes</strong><p>{a.diagnosis}</p>{!a.invoice&&<p>{a.medications||"No medicines recorded"}</p>}</div>}
    <div className="actions">{role==="DOCTOR"&&a.status==="PENDING"&&<button disabled={busy} className="button" onClick={()=>act("/api/consultations/"+a.id+"/approve")}>Approve appointment</button>}
    {role==="DOCTOR"&&a.status==="CONFIRMED"&&<button disabled={busy} className="button" onClick={()=>act("/api/consultations/"+a.id+"/start")}>Start consultation</button>}
    {role!=="CLINIC_ADMIN"&&["PENDING","CONFIRMED"].includes(a.status)&&(confirm?<><span>Cancel this appointment?</span><button className="outline" disabled={busy} onClick={()=>act("/api/appointments/cancel/"+a.id,null,"PUT")}>Yes, cancel</button><button className="text-button" onClick={()=>setConfirm(false)}>Keep appointment</button></>:<button className="text-button" onClick={()=>setConfirm(true)}>Cancel appointment</button>)}</div>
    {role==="DOCTOR"&&a.status==="IN_PROGRESS"&&<CarePlan fee={a.consultationFeeSnapshot??a.doctor.consultationFee} busy={busy} submit={body=>act("/api/consultations/"+a.id+"/care-plan",body)}/>}
    {a.invoice&&<Invoice a={a} role={role} busy={busy} act={act} demo={demo}/>}
  </article>;
}
function CarePlan({fee,busy,submit}) {
  const [rows,setRows]=useState([]),[referral,setReferral]=useState(false);
  function update(index,key,value){setRows(old=>old.map((r,i)=>i===index?{...r,[key]:value}:r));}
  function send(e){e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));submit({diagnosis:values.diagnosis,medicines:referral?[]:rows.map(r=>({...r,quantity:Number(r.quantity),unitPrice:Number(r.unitPrice)})),inPersonRequired:referral,referralNote:values.referralNote||"",outcome:values.outcome});}
  const total=Number(fee)+(referral?0:rows.reduce((s,r)=>s+Number(r.quantity)*Number(r.unitPrice),0));
  return <form className="inline-form care-plan" onSubmit={send}><h4>Care plan & prescription</h4><label>Diagnosis<textarea name="diagnosis" required maxLength={5000}/></label><label className="check-label"><input type="checkbox" checked={referral} onChange={e=>setReferral(e.target.checked)}/>In-person check required</label>
    {referral?<label>In-person assessment instructions<textarea name="referralNote" required maxLength={2000}/><small>No medicine delivery order will be created for this referral.</small></label>:<><div className="medicine-editor">{rows.map((r,i)=><fieldset key={i}><legend>Medicine {i+1}</legend><label>Medicine name<input aria-label={"Medicine name "+(i+1)} required maxLength={120} value={r.name} onChange={e=>update(i,"name",e.target.value)}/></label><label>Dosage & instructions<input aria-label={"Instructions "+(i+1)} required maxLength={500} value={r.instructions} onChange={e=>update(i,"instructions",e.target.value)}/></label><label>Quantity<input aria-label={"Quantity "+(i+1)} type="number" min="1" max="1000" step="1" required value={r.quantity} onChange={e=>update(i,"quantity",e.target.value)}/></label><label>Unit price (₹)<input aria-label={"Unit price "+(i+1)} type="number" min="0" max="100000" step=".01" required value={r.unitPrice} onChange={e=>update(i,"unitPrice",e.target.value)}/></label><button type="button" className="text-button" onClick={()=>setRows(old=>old.filter((_,idx)=>idx!==i))}>Remove medicine {i+1}</button></fieldset>)}</div><button type="button" className="outline" disabled={rows.length>=30} onClick={()=>setRows(old=>[...old,{name:"",instructions:"",quantity:1,unitPrice:""}])}>Add medicine</button><small>Leave the list empty if no medicine is prescribed.</small></>}
    <label>Recorded outcome<select name="outcome" defaultValue="NOT_RECORDED"><option value="NOT_RECORDED">Not yet assessed</option><option value="FOLLOW_UP">Follow-up needed</option><option value="IMPROVED">Patient improved</option><option value="RECOVERED">Patient reported recovered</option></select></label>
    <div className="invoice-total">Doctor fee {money(fee)} · Invoice total {money(total)}</div><button className="button" disabled={busy}>Complete consultation</button>
  </form>;
}
function Invoice({a,role,busy,act,demo}) {
  const inv=a.invoice;const items=JSON.parse(inv.itemsJson);const [confirm,setConfirm]=useState(false);
  function download(){
    const lines=["CARELINK — DEMO INVOICE (not a tax invoice)","Invoice CL-"+inv.id,"Visit #"+a.id,"Patient: "+a.patient.fullName,"Doctor: "+name(a.doctor),"Issued: "+date(inv.issuedAt),"Status: "+inv.status,"Consultation: "+money(inv.doctorFee),...items.map(m=>m.name+" × "+m.quantity+" @ "+money(m.unitPrice)+" = "+money(m.quantity*m.unitPrice)+"; "+m.instructions),"Medicines: "+money(inv.medicineTotal),"Total: "+money(inv.total),"In-person check required: "+(inv.inPersonRequired?"Yes":"No"),inv.referralNote||"","No real payment or dispatch has occurred."];
    const url=URL.createObjectURL(new Blob([lines.join("\n")],{type:"text/plain;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download="CareLink-invoice-"+inv.id+".txt";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
  }
  return <section className="invoice"><div className="section-head"><h4>Prescription & invoice CL-{inv.id}</h4><span className="status">{inv.status.replaceAll("_"," ")}</span></div>
    {inv.inPersonRequired&&<div className="referral"><strong>In-person check required</strong><p>{inv.referralNote}</p><small>Follow your clinician’s instructions. Medicine delivery is not available for this referral.</small></div>}
    {items.length>0?<div className="table-scroll"><table><thead><tr><th>Medicine & instructions</th><th>Quantity</th><th>Unit price</th><th>Amount</th></tr></thead><tbody>{items.map((m,i)=><tr key={i}><td><strong>{m.name}</strong><small>{m.instructions}</small></td><td>{m.quantity}</td><td>{money(m.unitPrice)}</td><td>{money(m.quantity*m.unitPrice)}</td></tr>)}</tbody></table></div>:<p>No medicines prescribed.</p>}
    <dl className="invoice-summary"><div><dt>Doctor consultation fee</dt><dd>{money(inv.doctorFee)}</dd></div><div><dt>Medicine charges</dt><dd>{money(inv.medicineTotal)}</dd></div><div className="invoice-total"><dt>Total</dt><dd>{money(inv.total)}</dd></div></dl><p className="muted">Issued {date(inv.issuedAt)} · Outcome: {inv.outcome.replaceAll("_"," ").toLowerCase()}</p>
    {role==="PATIENT"&&inv.status==="ISSUED"&&<button className="button" disabled={busy} onClick={()=>act("/api/appointments/"+a.id+"/accept")}>{items.length?"Accept medicines & invoice":"Accept consultation invoice"}</button>}
    {role==="PATIENT"&&inv.status==="ACCEPTED"&&(demo?<div className="demo-banner"><p>Demo checkout: no real charge or delivery will take place.</p>{confirm?<><button className="button" disabled={busy} onClick={()=>act("/api/appointments/"+a.id+"/demo-pay")}>Confirm demo payment {money(inv.total)}</button><button className="text-button" onClick={()=>setConfirm(false)}>Go back</button></>:<button className="button" onClick={()=>setConfirm(true)}>Pay {money(inv.total)} (demo)</button>}</div>:<p>Payment checkout is not configured. Contact the clinic.</p>)}
    {inv.status==="DEMO_PAID"&&<div className="demo-banner" role="status">{inv.deliveryStatus==="DEMO_QUEUED"?"Demo order placed — your medicine delivery is queued. In a live service, your medicines would be delivered soon. No medicine has actually been dispatched.":"Demo payment recorded. "+(inv.inPersonRequired?"Please attend the in-person assessment.":"No medicine delivery is required.")}</div>}
    <div className="actions"><button className="text-button" onClick={download}>Download invoice</button></div>
  </section>;
}
function Schedule({api,visits,refresh}) {
  const [slots,setSlots]=useState([]),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[removing,setRemoving]=useState(null);
  const load=useCallback(()=>api("/api/schedule/my").then(setSlots).catch(e=>setError(e.message)),[api]);
  useEffect(()=>{load();},[load]);
  async function create(e){e.preventDefault();const form=e.currentTarget;const params=new URLSearchParams(Object.fromEntries(new FormData(form)));setBusy(true);setError("");try{await api("/api/schedule/slots?"+params,{method:"POST"});form.reset();setMessage("Availability added.");await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function remove(id){setBusy(true);setError("");try{await api("/api/schedule/slots/"+id,{method:"DELETE"});setRemoving(null);setMessage("Availability removed.");await load();refresh();}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <section><h2>Your availability</h2><ErrorBox error={error}/>{message&&<p role="status">{message}</p>}<form className="schedule-form" onSubmit={create}><label>Starts<input name="start" type="datetime-local" required/></label><label>Ends<input name="end" type="datetime-local" required/></label><button className="button" disabled={busy}>Add availability</button></form><div className="slot-list">{slots.filter(s=>!s.withdrawn&&new Date(s.endTime)>new Date()).map(s=>{const visit=visits.find(a=>a.slot.id===s.id&&a.status!=="CANCELLED");return <article key={s.id} className="slot-item"><strong>{date(s.startTime)}</strong><small>Until {date(s.endTime)}</small><span className="status">{visit?labels[visit.status]:s.booked?"Booked":"Available"}</span>{visit&&<span>{visit.patient.fullName}</span>}{!s.booked&&(removing===s.id?<><span>Remove this available slot?</span><button className="text-button" disabled={busy} onClick={()=>remove(s.id)}>Confirm removal</button><button className="text-button" onClick={()=>setRemoving(null)}>Keep slot</button></>:<button className="text-button" onClick={()=>setRemoving(s.id)}>Remove slot</button>)}</article>;})}</div></section>;
}
function Accounts({api,doctors,loadDoctors}) {
  const [patients,setPatients]=useState([]),[error,setError]=useState(""),[message,setMessage]=useState(""),[pending,setPending]=useState(null),[busy,setBusy]=useState(false);
  const load=useCallback(()=>api("/api/patients").then(setPatients).catch(e=>setError(e.message)),[api]);
  useEffect(()=>{load();},[load]);
  async function add(e){e.preventDefault();const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));setBusy(true);setError("");try{await api("/api/doctors",{method:"POST",body:JSON.stringify({...data,consultationFee:Number(data.consultationFee),yearsOfExperience:Number(data.yearsOfExperience)})});form.reset();await loadDoctors();setMessage("Doctor account created. Share their credentials privately.");}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function deactivate(){setBusy(true);setError("");try{await api("/api/"+pending.type+"/"+pending.id,{method:"DELETE"});setPending(null);await load();await loadDoctors();}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <section><h2>Clinic accounts</h2><ErrorBox error={error}/>{message&&<p role="status">{message}</p>}<details className="create-doctor"><summary>Add a doctor</summary><form className="inline-form" onSubmit={add}><label>Doctor full name<input name="fullName" required maxLength={100}/></label><label>Doctor email<input name="email" type="email" required/></label><label>Initial password<input name="password" type="password" required minLength={12} maxLength={72} autoComplete="new-password"/></label><label>Specialization<input name="specialization" required/></label><label>Consultation fee (₹)<input name="consultationFee" type="number" min=".01" max="100000" step=".01" required/></label><label>Years of experience<input name="yearsOfExperience" type="number" min="0" step="1" required/></label><button className="button" disabled={busy}>Create doctor account</button></form></details>
    {pending&&<div className="notice" role="alert">Deactivate {pending.name}? History will be retained.<button disabled={busy} onClick={deactivate}>Confirm deactivation</button><button onClick={()=>setPending(null)}>Keep active</button></div>}<div className="admin-grid"><section><h3>Doctors ({doctors.length})</h3>{doctors.map(d=><div className="list-row" key={d.id}><span>Dr. {name(d)}<small>{d.account.email} · {money(d.consultationFee)}</small></span><button className="text-button" onClick={()=>setPending({type:"doctors",id:d.id,name:name(d)})}>Deactivate</button></div>)}</section><section><h3>Patients ({patients.length})</h3>{patients.map(p=><div className="list-row" key={p.id}><span>{p.fullName}<small>{p.account.email}</small></span>{p.account.active?<button className="text-button" onClick={()=>setPending({type:"patients",id:p.id,name:p.fullName})}>Deactivate</button>:<span className="status">Inactive</span>}</div>)}</section></div></section>;
}
