import { test, expect } from "@playwright/test";
import fs from "node:fs";
import { randomBytes } from "node:crypto";
const settings = Object.fromEntries(fs.readFileSync(new URL("../../.local-carelink.properties", import.meta.url), "utf8")
  .split(/\r?\n/).filter(l=>l.includes("=")).map(l=>[l.slice(0,l.indexOf("=")), l.slice(l.indexOf("=")+1)]));
const doctorPassword=settings["carelink.demo.doctor-password"];
const adminPassword=settings["carelink.demo.admin-password"];
async function login(page,email,password,role) {
  await page.goto("/");
  await page.getByRole("navigation").getByRole("button",{name:"Sign in",exact:true}).click();
  if(role) await page.getByRole("button",{name:role,exact:true}).click();
  await page.getByLabel("Email address").fill(email);
  await page.getByLabel("Password",{exact:true}).fill(password);
  await page.locator("form").getByRole("button",{name:"Sign in",exact:true}).click();
  await expect(page.getByRole("heading",{name:/Welcome back,/})).toBeVisible();
}
test("stale session recovers and public doctor discovery works", async ({page})=>{
  const crashes=[];page.on("pageerror",e=>crashes.push(e.message));
  await page.addInitScript(()=>sessionStorage.setItem("carelink_token","invalid-old-token"));
  await page.goto("/");
  await expect(page.getByRole("heading",{name:"Welcome back."})).toBeVisible();
  await page.getByRole("navigation").getByRole("button",{name:"Doctors",exact:true}).click();
  await expect(page.locator(".doctor")).toHaveCount(3);
  await expect(page.getByText("Dr. Ananya Rao",{exact:true})).toBeVisible();
  expect(crashes).toEqual([]);
});
test("patient, doctor and admin complete the real PostgreSQL journey", async ({browser})=>{
  const context=await browser.newContext();
  const patient=await context.newPage();
  const crashes=[]; patient.on("pageerror",e=>crashes.push(e.message));
  const stamp=Date.now();
  const email="browser-"+stamp+"@carelink.test";
  const password=randomBytes(18).toString("base64");
  await patient.goto("/");
  await patient.getByRole("button",{name:"Create account",exact:true}).click();
  await patient.getByLabel("Full name").fill("Browser Test "+stamp);
  await patient.getByLabel("Email address").fill(email);
  await patient.getByLabel("Password",{exact:false}).fill(password);
  await patient.getByLabel("Blood group").selectOption("O+");
  await patient.getByLabel("Emergency contact").fill("0000000000");
  await patient.getByRole("button",{name:"Create my account"}).click();
  await expect(patient.getByRole("heading",{name:/Welcome back,/})).toBeVisible();
  await patient.reload();
  await expect(patient.getByText("Signed in as "+email)).toBeVisible();
  await expect(patient.locator(".doctor")).toHaveCount(3);
  await patient.locator(".doctor").filter({hasText:"Ananya Rao"}).getByRole("button").click();
  await expect(patient.getByLabel("Appointment time").locator("option")).not.toHaveCount(1);
  await patient.getByLabel("Appointment time").selectOption({index:1});
  const reason="Browser journey "+stamp;
  await patient.getByLabel("What would you like help with?").fill(reason);
  await patient.getByRole("button",{name:"Confirm appointment"}).click();
  await expect(patient.locator(".visit-card").filter({hasText:reason})).toContainText("In queue");

  const doctor=await context.newPage();
  await login(doctor,"cardiologist@carelink.com",doctorPassword,"Doctor");
  await patient.reload();
  await doctor.reload();
  await expect(patient.getByText("Signed in as "+email)).toBeVisible();
  await expect(doctor.getByText("Signed in as cardiologist@carelink.com")).toBeVisible();
  await patient.getByRole("navigation",{name:"Dashboard sections"}).getByRole("button",{name:"My profile"}).click();
  await expect(patient.locator(".profile-card")).toContainText("Browser Test "+stamp);
  await expect(patient.locator(".profile-card")).toContainText("O+");
  await patient.getByRole("navigation",{name:"Dashboard sections"}).getByRole("button",{name:"Dashboard",exact:true}).click();
  const visit=doctor.locator(".visit-card").filter({hasText:reason});
  await visit.getByRole("button",{name:"Approve appointment"}).click();
  await expect(visit).toContainText("In queue · confirmed");
  await expect(patient.locator(".visit-card").filter({hasText:reason})).toContainText("In queue · confirmed");
  await visit.getByRole("button",{name:"Start consultation"}).click();
  await expect(visit).toContainText("In progress");
  await expect(patient.locator(".visit-card").filter({hasText:reason})).toContainText("In progress");
  await expect(patient.locator(".current-count strong")).toHaveText("1");
  await visit.getByLabel("Diagnosis").fill("Synthetic browser test completed.");
  await visit.getByRole("button",{name:"Add medicine",exact:true}).click();
  await visit.getByLabel("Medicine name 1",{exact:true}).fill("Synthetic test medicine");
  await visit.getByLabel("Instructions 1",{exact:true}).fill("Test instructions only");
  await visit.getByLabel("Quantity 1",{exact:true}).fill("2");
  await visit.getByLabel("Unit price 1",{exact:true}).fill("25.50");
  // Live refreshes must not clear the doctor's unfinished prescription.
  await doctor.waitForTimeout(3600);
  await expect(visit.getByLabel("Diagnosis")).not.toHaveValue("");
  await visit.getByRole("button",{name:"Complete consultation"}).click();
  await expect(visit).toContainText("Completed");
  await expect(patient.locator(".visit-card").filter({hasText:reason})).toContainText("Synthetic browser test completed.");
  const invoice=patient.locator(".visit-card").filter({hasText:reason});
  await invoice.getByRole("button",{name:"Accept medicines & invoice"}).click();
  await invoice.getByRole("button",{name:/^Pay .*demo/}).click();
  await invoice.getByRole("button",{name:/Confirm demo payment/}).click();
  await expect(invoice).toContainText("DEMO PAID");
  await expect(visit).toContainText("DEMO PAID");
  await expect(patient.locator(".current-count strong")).toHaveText("0");
  await expect(invoice).toContainText("No medicine has actually been dispatched.");
  const downloadPromise=patient.waitForEvent("download");
  await invoice.getByRole("button",{name:"Download invoice"}).click();
  expect((await downloadPromise).suggestedFilename()).toContain("CareLink-invoice");
  await doctor.getByRole("navigation",{name:"Dashboard sections"}).getByRole("button",{name:"Availability",exact:true}).click();
  // Exercise creating a doctor slot in a future year, unique to this run.
  const doctorToken=await doctor.evaluate(()=>sessionStorage.getItem("carelink_token"));
  const existingSlots=await (await doctor.request.get("/api/schedule/my",{headers:{Authorization:"Bearer "+doctorToken}})).json();
  const base=Math.max(Date.now(),...existingSlots.map(s=>new Date(s.endTime).getTime()))+86400000*2;
  const start=new Date(base).toISOString().slice(0,16);
  const end=new Date(base+1800000).toISOString().slice(0,16);
  await doctor.getByLabel("Starts",{exact:true}).fill(start);
  await doctor.getByLabel("Ends",{exact:true}).fill(end);
  await doctor.getByRole("button",{name:"Add availability"}).click();
  await expect(doctor.getByText("Availability added.",{exact:true})).toBeVisible();
  const availableSlots=doctor.locator(".slot-item").filter({has:doctor.getByRole("button",{name:"Remove slot",exact:true})});
  const removable=availableSlots.last();
  await removable.getByRole("button",{name:"Remove slot",exact:true}).click();
  await doctor.getByRole("button",{name:"Confirm removal",exact:true}).click();
  await expect(doctor.getByText("Availability removed.",{exact:true})).toBeVisible();

  // A second booking exercises cancellation and slot release.
  await patient.locator(".doctor").filter({hasText:"Meera Iyer"}).getByRole("button").click();
  await expect(patient.getByLabel("Appointment time").locator("option")).not.toHaveCount(1);
  await patient.getByLabel("Appointment time").selectOption({index:1});
  await patient.getByLabel("What would you like help with?").fill("Cancellation "+stamp);
  await patient.getByRole("button",{name:"Confirm appointment"}).click();
  const cancelled=patient.locator(".visit-card").filter({hasText:"Cancellation "+stamp});
  await cancelled.getByRole("button",{name:"Cancel appointment",exact:true}).click();
  await cancelled.getByRole("button",{name:"Yes, cancel"}).click();
  await expect(cancelled).toContainText("Cancelled");

  const adminContext=await browser.newContext();const admin=await adminContext.newPage();
  await login(admin,"admin@carelink.com",adminPassword,"Administrator");
  await expect(admin.locator(".visit-card").filter({hasText:reason})).toContainText("Completed");
  await admin.getByRole("navigation",{name:"Dashboard sections"}).getByRole("button",{name:"Doctors & patients",exact:true}).click();
  const patientRow=admin.locator(".list-row").filter({hasText:email});
  await patientRow.getByRole("button",{name:"Deactivate",exact:true}).click();
  await admin.getByRole("button",{name:"Confirm deactivation"}).click();
  await expect(patientRow).toContainText("Inactive");
  await patient.reload();
  await expect(patient.getByRole("heading",{name:"Welcome back."})).toBeVisible();
  await admin.getByRole("button",{name:"Sign out",exact:true}).click();
  await expect(admin.getByRole("heading",{name:"Care, without the running around."})).toBeVisible();
  expect(crashes).toEqual([]);
  await context.close();await adminContext.close();
});
for (const email of ["dermatologist@carelink.com","physician@carelink.com"]) {
  test("doctor login: "+email,async({page})=>{
    await login(page,email,doctorPassword,"Doctor");
    await page.getByRole("navigation",{name:"Dashboard sections"}).getByRole("button",{name:"Availability",exact:true}).click();
    await expect(page.getByRole("heading",{name:"Your availability"})).toBeVisible();
    await page.reload();
    await expect(page.getByText("Signed in as "+email)).toBeVisible();
    await page.setViewportSize({width:390,height:844});
    await expect(page.locator(".header-counters")).toBeVisible();
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
    await page.route("**/api/dashboard",route=>route.abort());
    await expect(page.getByText("Reconnecting — your last update is still shown")).toBeVisible();
    await expect(page.locator(".completed-count strong")).not.toHaveText("…");
    await page.unroute("**/api/dashboard");
    await expect(page.getByText("Updates automatically · every few seconds")).toBeVisible();
    await page.screenshot({path:"test-results/doctor-mobile-live.png",fullPage:true});
  });
}
test("mobile navigation fits and account forms remain usable",async({page})=>{
  await page.setViewportSize({width:390,height:844});
  await page.goto("/");
  await page.getByRole("navigation").getByRole("button",{name:"Sign in",exact:true}).click();
  await expect(page.getByRole("button",{name:"Administrator",exact:true})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
});

test("admin adds a doctor and in-person care has a fee-only invoice",async({browser})=>{
  const adminContext=await browser.newContext(), doctorContext=await browser.newContext(), patientContext=await browser.newContext();
  const admin=await adminContext.newPage(), doctor=await doctorContext.newPage(), patient=await patientContext.newPage();
  const stamp=Date.now(), doctorEmail="new-doctor-"+stamp+"@carelink.test", patientEmail="referral-"+stamp+"@carelink.test";
  const password=randomBytes(18).toString("base64");
  await login(admin,"admin@carelink.com",adminPassword,"Administrator");
  await admin.getByRole("navigation",{name:"Dashboard sections"}).getByRole("button",{name:"Doctors & patients"}).click();
  await admin.getByText("Add a doctor",{exact:true}).click();
  await admin.getByLabel("Doctor full name").fill("Workflow Test Doctor");
  await admin.getByLabel("Doctor email").fill(doctorEmail);
  await admin.getByLabel("Initial password").fill(password);
  await admin.getByLabel("Specialization",{exact:true}).fill("General medicine");
  await admin.getByLabel("Consultation fee (₹)").fill("600");
  await admin.getByLabel("Years of experience").fill("5");
  await admin.getByRole("button",{name:"Create doctor account"}).click();
  await expect(admin.getByText("Doctor account created. Share their credentials privately.")).toBeVisible();
  await login(doctor,doctorEmail,password,"Doctor");
  await doctor.getByRole("navigation",{name:"Dashboard sections"}).getByRole("button",{name:"Availability"}).click();
  const start=new Date(Date.now()+86400000*10).toISOString().slice(0,16);
  const end=new Date(Date.now()+86400000*10+1800000).toISOString().slice(0,16);
  await doctor.getByLabel("Starts",{exact:true}).fill(start);
  await doctor.getByLabel("Ends",{exact:true}).fill(end);
  await doctor.getByRole("button",{name:"Add availability"}).click();
  await expect(doctor.getByText("Availability added.")).toBeVisible();
  const registration=await patient.request.post("/api/auth/register",{data:{email:patientEmail,password,fullName:"Referral Test Patient",bloodGroup:"O+",emergencyContact:"0000000000"}});
  expect(registration.ok()).toBeTruthy();
  await login(patient,patientEmail,password,"Patient");
  await patient.getByRole("navigation",{name:"Dashboard sections"}).getByRole("button",{name:"Doctors",exact:true}).click();
  await patient.locator(".doctor").filter({hasText:"Workflow Test Doctor"}).getByRole("button").click();
  await expect(patient.getByLabel("Appointment time").locator("option")).toHaveCount(2);
  await patient.getByLabel("Appointment time").selectOption({index:1});
  await patient.getByLabel("What would you like help with?").fill("Referral scenario "+stamp);
  await patient.getByRole("button",{name:"Confirm appointment"}).click();
  await doctor.getByRole("navigation",{name:"Dashboard sections"}).getByRole("button",{name:"Appointments",exact:true}).click();
  const visit=doctor.locator(".visit-card").filter({hasText:"Referral scenario "+stamp});
  await visit.getByRole("button",{name:"Approve appointment"}).click();
  await visit.getByRole("button",{name:"Start consultation"}).click();
  await visit.getByLabel("Diagnosis").fill("Synthetic referral test.");
  await visit.getByLabel("In-person check required",{exact:true}).check();
  await visit.getByLabel("In-person assessment instructions").fill("Attend the clinic for an examination. Test only.");
  await visit.getByLabel("Recorded outcome").selectOption("FOLLOW_UP");
  await visit.getByRole("button",{name:"Complete consultation"}).click();
  await expect(visit.getByText("In-person check required",{exact:true})).toBeVisible();
  await expect(doctor.locator(".completed-count strong")).toHaveText("1");
  const invoice=patient.locator(".visit-card").filter({hasText:"Referral scenario "+stamp});
  await invoice.getByRole("button",{name:"Accept consultation invoice"}).click();
  await invoice.getByRole("button",{name:/^Pay .*demo/}).click();
  await invoice.getByRole("button",{name:/Confirm demo payment/}).click();
  await expect(invoice).toContainText("Please attend the in-person assessment.");
  await expect(invoice).not.toContainText("delivery is queued");
  await expect(patient.locator(".completed-count strong")).toHaveText("1");
  await doctor.getByRole("navigation",{name:"Dashboard sections"}).getByRole("button",{name:"Invoices & earnings"}).click();
  await expect(doctor.locator(".metric").filter({hasText:"Doctor earnings (demo)"})).toContainText("600.00");
  await patient.evaluate(()=>window.scrollTo(0,0));
  await patient.screenshot({path:"test-results/patient-referral.png",fullPage:true});
  await admin.getByRole("navigation",{name:"Dashboard sections"}).getByRole("button",{name:"Invoices & earnings"}).click();
  await admin.evaluate(()=>window.scrollTo(0,0));
  await admin.screenshot({path:"test-results/admin-revenue.png",fullPage:true});
  await admin.getByRole("navigation",{name:"Dashboard sections"}).getByRole("button",{name:"Doctors & patients"}).click();
  for(const email of [patientEmail,doctorEmail]){
    const row=admin.locator(".list-row").filter({hasText:email});
    await row.getByRole("button",{name:"Deactivate",exact:true}).click();
    await admin.getByRole("button",{name:"Confirm deactivation"}).click();
    if(email===patientEmail) await expect(row).toContainText("Inactive"); else await expect(row).toHaveCount(0);
  }
  await adminContext.close();await doctorContext.close();await patientContext.close();
});
